### PR TITLE
Changed arguments to parameters

### PR DESCRIPTION
**Pull request by JoeH8rs**
Function parameters are the names listed in the function definition.

Function arguments are the real values passed to (and received by) the function.

Changed parameter names to make functions reusable and more logical to the student.

### CODE REVIEW

**Comment by jrobber** [comment]
Pull down the latest code, fix conflcts then re-push.  It should update this code review and let me merge.

**Comment by JoeH8rs** [comment]
OK

**Comment by JoeH8rs** [comment]
Done

**Comment by asBrettisay** [comment]
In the language in these instructions, argument is correct, because they are being given to the function.

**Pull request closed without merging**
